# Generated by Django 5.1.7 on 2025-03-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertodo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
