# Generated by Django 5.1.7 on 2025-03-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_API', '0003_usertodo_is_staff_usertodo_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertodo',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
